/**
 * Created by mac002 on 7/31/17.
 */
const DB_SET_PROTECTED = 'DB_SET_PROTECTED';
const LANGUAGE_SET_CODE = 'LANGUAGE_SET_CODE';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';

export default {
  DB_SET_PROTECTED
  , LANGUAGE_SET_CODE
  , USER_LOGIN
  , USER_LOGOUT
};